### PR TITLE
Uploaded API implementations and object classes

### PR DESCRIPTION
**Pull request by babbo65**

### CODE REVIEW

**Comment by babbo65** [comment]
Accidentally re uploaded API interfaces, may have deleted unnecessary comments but should be same files/interfaces, up to you if you want to delete those ones or just rewrite

**Review by colinm0125 — COMMENTED** [review]
Forgot constructors for API methods. Everything else looks good to me.

**Comment by babbo65** [comment]
Added constructors and committed to this branch

**Comment by babbo65** [comment]
Also deleted duplicate files

**Review by colinm0125 — APPROVED** [review]
Looking better, thanks

**Pull request merged**
